name: deploy
jobs:
  deploy-on-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
      - run: npm ci
      - run: npm run build
        uses: actions/checkout@v3

      - name: Deploy to github-pages
      - run: |
          chmod +x ./deploy.sh
          ./deploy.sh
        shell: bash
