name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-on-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build project
        run: npm ci && npm run build

      - name: Deploy to github-pages
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
        shell: bash
